### ISSUE TITLE
Error "git -m"

### ISSUE THREAD

**Issue by Drasek** [rayozzie/ttn-resin-gateway-rpi#3]
Hello, i try to use your manual to set up our gateway and the line:

`git add . git -m "first upload of ttn files to resin" git push resin master`

gives me a error: error: `unknown switch `m'`

I am on a Mac (OSX, running Sierra), just using the standard terminal. Thank you for your help!

**Comment by jpmeijers** [comment]
The newlines went missing. Try:
```
git add .
git commit -m "first upload of ttn files to resin"
git push resin master
```

**Comment by rayozzie** [comment]
fixed the README.md

**Comment by Drasek** [comment]
The "comit" is needed in the second line and still missing readme.md, could you please add it?

**Comment by rayozzie** [comment]
right you are.  fixed again.
